name: tests
'on':
  push:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-18.04
    name: Node ${{ matrix.node }} (Linux)
    strategy:
      matrix:
        node:
          - '10'
          - '12'
          - '14'
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test

  test-windows:
    runs-on: windows-2019
    name: Node ${{ matrix.node }} (Windows)
    strategy:
      matrix:
        node:
          - '10'
          - '12'
          - '14'
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test

  test-targets:
    runs-on: ubuntu-18.04
    name: ${{ matrix.targets.name }}
    strategy:
      matrix:
        targets:
          - name: 'Lint'
            target: 'lint'
          - name: 'Coverage'
            target: 'coverage'

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - run: npm install
      - run: npm run ${{ matrix.targets.target }}
      - name: Upload coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ matrix.targets.target == 'coverage' }}
